### ISSUE TITLE
Tooltipster v4

### ISSUE THREAD

**Issue by louisameline** [IMIO/collective.js.tooltipster#1]
Hi, just saw this repo. FYI,

> Using version 3.3.0 because it works with jQuery 1.7+ where version 4+ works only with jQuery 1.10+...

is incorrect. From the doc:

> Compatibility note: jQuery 1.7 is enough except if you need SVG support in IE (then use jQuery 1.10+). Tooltipster does not work at all with jQuery 1.8 in IE9.

**Comment by gbastien** [comment]
Hi @louisameline 

I tested github master and as far as I remember I had problems with some undefined "geo" or so...  We first tried with 3.3.0 and everything was working fine, so we just get back to it.  We are stucked for now with jQuery 1.7.2 so as version 3.3.0 did what we needed, we use it.  But maybe I (or you? ;-)) can adapt the description page about this.

Thank you,

Gauthier

**Comment by louisameline** [comment]
You're welcome. Well I was just giving you a heads up in case you wanted to use v4 :)
If you find that something in v4 is not working with jquery 1.7, let me know and I'll fix it or update Tooltipster's documentation.
https://jsfiddle.net/5xqqmrt6/13/
Thank you.

**Comment by louisameline** [comment]
We had a bug in v4 related to geo but only in IE. Try again with the latest version (4.1.5).

**Comment by gbastien** [comment]
OK, as we are on it these days, I will try again with last release.  I probably tried with Firefox or Chrome.

I prefer to use last version if it works for us obviously, I will come back to you when possible.

Thank you,

Gauthier

**Comment by gbastien** [comment]
Hi @louisameline 

we finally had time to move to last version (4.2.6) and after minor changes when using Ajax, it works ;-)

Thank you to warn me that version 4 should work with jQuery 1.7.x

Gauthier
